# Generated by Django 2.0.2 on 2018-10-09 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20181009_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 13, 18, 15, 45716, tzinfo=utc)),
        ),
    ]
