# Generated by Django 2.0.2 on 2018-10-11 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20181010_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('score', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='top_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.PostComment'),
        ),
    ]
